image: Ubuntu1804  # образ для сборки

stack: jdk 11

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - java -jar ./artifact/app-ibank.jar -P:profile=test &

build_script:
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)
